---
title: "R Notebook"
output: word_document
editor_options: 
  chunk_output_type: console
---
#How to Get SRA files
##Taken from https://www.biostars.org/p/93494/
##SRA documentation https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=toolkit_doc&f=fastq-dump

Bioconductor Setup
```{r}
source('http://bioconductor.org/biocLite.R')
biocLite('SRAdb')
biocLite('limma')
biocLite('ShortRead')
biocLite('Rbowtie')
```

Load Libraries
```{r}
library(SRAdb)
library(DBI)
library(ShortRead)
library(R.utils)
library(curl)
library(Rbowtie)
library(Rsamtools)
library(devtools)
```

Setup for SRA
```{r}
#srafile = getSRAdbFile() #only need to run once
con = dbConnect(RSQLite::SQLite(), srafile)
```

#Dataset 1 - list the SRA files, and then download
```{r}
##Paper: https://www.nature.com/articles/nature14546#t1
##SRA Location: https://www.ncbi.nlm.nih.gov/sra/SRX874253[accn]
listSRAfile('SRP047082',con)
getSRAfile('SRP047082',con,fileType='sra')
```

#Example
```{r}
refFiles <- dir(system.file(package="Rbowtie","samples","refs"),full=TRUE)
indexDir<-file.path(tempdir(),"refsIndex")
temp<-bowtie_build(references=refFiles,outdir=indexDir,prefix="index",force=TRUE)

readsFiles<- system.file(package="Rbowtie", "samples", "reads","reads.fastq")
samFiles <- file.path(tempdir(),"alignments.sam")
bowtie(sequences=readsFiles, index=file.path(indexDir,"index"),
       outfile=samFiles,
       sam=TRUE, best=TRUE, force=TRUE)

#Version 2
refFiles <- "C:\\Program Files\\Git\\Coding\\GMU\\BINF996_Summer\\chrM.fa"
indexDir<-file.path(tempdir(),"refsIndex")
temp<-bowtie_build(references=refFiles,outdir=indexDir,prefix="index",force=TRUE)

readsFiles<- system.file(package="Rbowtie", "samples", "reads","reads.fastq")
samFiles <- "C:\\Program Files\\Git\\Coding\\GMU\\BINF996_Summer\\test.sam"
bowtie(sequences=readsFiles, index=file.path(indexDir,"index"),
       outfile=samFiles,
       sam=TRUE, best=TRUE, force=TRUE)
```

#Dataseread.t 2 - 28 samples from twin study
```{r}
#Dataset information
##Paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3441121/
##SRA Location: https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?study=SRP010986

#Make sure the list is correct
listSRAfile('SRP010986',con)

#Change directory and download files
{setwd("/Users/sevillas2/Google\ Drive/My\ Documents/Education/George\ Mason\ University/BINF996/2018_Summer/SRA_SRP010986/")
getSRAfile('SRP010986',con,fileType='sra')
}

#Read in the CSV to get names
#Remove paired reads for consistency - "SRR420833",	"SRR420832", "SRR420831"
sri <- read.csv("/Users/slsevilla/Google\ Drive/My\ Documents/Education/George\ Mason\ University/BINF996/2018_Summer/SRA_SRP010986/SraRunTable_SRP010986.csv",stringsAsFactors = FALSE)
sri <- sri[-c(6,7,8),]

#Assign sample name to rows
row.names(sri) <- sri$Run
files <-as.list(sri$Run)

for(f in files) {
 #Create a list of the files, and determine their ftp location
 temp <- getFASTQinfo(in_acc=f,sra_con=con)
 temp <- as.character(temp$ftp)
 
 #Add location to database
 sri[f,"Location"] <- temp
 
 #Determine FastQ GZ name
 tempname <- paste(f,".fastq.gz")
 tempname <- gsub(" .fastq",".fastq",tempname)
 sri[f,"GZip"] <- tempname
 
 #Print as files go
 print(temp)
 
 #Download file
 #curl_download(temp,tempname)
}

#Unzip the GZ files
files <- as.list(sri[1,"GZip"])
for (f in files){
 gunzip(f)
}

#Download the reference file, and unzip
refFiles <- "chrM.fa.gz"
gunzip (refFile)

#Create index
refFiles <- "chrM.fa"
indexDir <- file.path(tempdir(), "refsIndex")
tmp <- bowtie_build(references=refFiles, outdir=indexDir, prefix="index", force=TRUE)
head(tmp)

#Create directory to read in and for final file names
files <- as.list(sri$Run)

for (f in files){
 #Create FASTQ File
 temp <- sri[f,"Run"]
 temp <- paste(temp,".fastq")
 temp <- paste("C:\\Program Files\\Git\\Coding\\GMU\\BINF996_Summer\\",temp)
 temp <- gsub(" .fastq",".fastq",temp)
 temp <- gsub("\\ ","\\",temp)
 sri[f,"FASTQ"]<- temp
 
 #Create SAM File location
 temp <- sri[f,"Run"]
 temp <- paste(temp,".sam")
 temp <- paste("C:\\Program Files\\Git\\Coding\\GMU\\BINF996_Summer\\",temp)
 temp <- gsub(" .sam",".sam",temp)
 temp <- gsub("\\ ","\\",temp)
 sri[f,"SAM"]<- temp
}

#Align sequences, create sam file
files <- as.character(as.list(sri$Run))
for (f in files){
 temp <- sri[f,"FASTQ"]
 finalname <- sri[f,"SAM"]
 bowtie(sequences=temp, outfile = finalname,index=file.path("index"), sam=TRUE, 
        best=TRUE, force=TRUE)
 #strtrim(readLines(finalname), 65)
}

#Convert to bam
samtools view -b -S file.sam > file.bam


```
