git_dir: 
  w: 'C:\Program Files\Git\Coding\gmu\dissertation\aim2\'
  m: '/home/sevillas2/git/gmu/dissertation/aim2/'
data_dir: 
  w: 'C:\Users\slsevilla\Google Drive\MyDocuments_Current\Education\George Mason University\Dissertation\data\aim2\Project_NP0084_MB\'
  m: '/data/sevillas2/gmu/aim2/output/'
analysis_dir: 
  w: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/analysis/aim2/'
  m: '/data/sevillas2/gmu/aim2/output/analysis/'
ref_dir: 
  w: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/data/ref/'
  m: '/data/sevillas2/gmu/ref/'
manifest_dir:
  w: 'C:\Program Files\Git\Coding\gmu\dissertation\aim2\manifest\'
  m: '/home/sevillas2/git/gmu/dissertation/aim2/manifest/'

clean_manifest: 'manifest.tsv'

