#!/usr/bin/env python3

import csv

def read_employees(csv_file_location,fieldnames=""):
        csv.register_dialect('empDialect',skipinitialspace=True, strict=True)

        if fieldnames !="":
                keynames = fieldnames.split(",")
                employee_file = csv.DictReader(open(csv_file_location), dialect = 'empDialect', fieldnames=keynames)
        else:
                employee_file = csv.DictReader(open(csv_file_location), dialect = 'empDialect')

        employee_list = []
        for data in employee_file:
                employee_list.append(data)

        return employee_list

employee_list = read_employees('/home/student-03-f36e630da82d/data/employees.csv')

def process_data(employee_list):
        department_list = []
        for employee_data in employee_list:
                department_list.append(employee_data['Department'])

        department_data = {}
        for department_name in set(department_list):
                department_data[department_name] = department_list.count(department_name)
        return department_data
