---
title: "R Notebook"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
Aids
-http://bioconductor.org/packages/3.7/bioc/vignettes/TarSeqQC/inst/doc/TarSeqQC-vignette.pdf


Load Libraries
```{r}
source("http://www.bioconductor.org/biocLite.R")
biocLite("TarSeqQC")
library("stringi")
library(TarSeqQC)
library(BiocParallel)
library(IRanges)
```

Load files
```{r}
bedFile<- system.file("extdata", "mybed.bed", package="TarSeqQC", mustWork=TRUE)
bamFile<- system.file("extdata", "mybam.bam", package = "TarSeqQC", mustWork = TRUE)
fastaFile<- system.file("extdata", "myfasta.fa", package = "TarSeqQC", mustWork = TRUE)
```

Create Panel
```{r}
BPPARAM<-bpparam()
myPanel<-TargetExperiment(bedFile, bamFile, fastaFile, feature="amplicon", attribute="coverage", BPPARAM=BPPARAM)
```

Set Features
```{r}
setFeature (myPanel) <- "amplicon"
setAttribute(myPanel)<- "coverage"
scanBamP<-ScanBamParam()
bamWhich(scanBamP)<-getBedFile(myPanel)
setScanBamP(myPanel)<-scanBamP
setPileupP(myPanel)<-PileupParam(max_depth=1000)
setFeaturePanel(myPanel)<-buildFeaturePanel(myPanel, BPPARAM)
setGenePanel(myPanel)<-summarizePanel(myPanel, BPPARAM)
```

Set pathways
```{r}
data(ampliPanel, package="TarSeqQC")
setBamFile(ampliPanel)<-system.file("extdata", "mybam.bam", package="TarSeqQC", mustWork=TRUE)
setFastaFile(ampliPanel)<-system.file("extdata", "myfasta.fa",package="TarSeqQC", mustWork=TRUE)
```

Review panel
```{r}
myPanel
```


