---
title: "R Notebook - RNA Analysis for BINF"
output: pdf_document
---
Following website: www.biocluster.ucr.edu/~rkaundal/workshops/R_mar2016/RNAseq.html


Install Packages
```{r}
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite(c("genomicFeatures", "AnnotationDbi", "systemPipeR", "systemPipeRdata"))
library(systemPipeR)
library(systemPipeRdata)
```

Create directory for test samples
```{r}
genWorkenvir(workflow="rnaseq")
setwd("rnaseq")
```

Send in input file with directory location
```{r}
targetspath <- system.file("extdata", "targets.txt", package="systemPipeR") 
read.delim(targetspath, comment.char = "#")
```

Split the paired end samples and preview
```{r}
targetspath <- system.file("extdata", "targetsPE.txt", package="systemPipeR")
read.delim(targetspath, comment.char="#")[1:2,1:6]
```

Define the comparisons
```{r}
readLines(targetspath)[1:4]
readComp(file=targetspath, format="vector", delim="-")
```
Define paramters
```{r}
parampath <- system.file("extdata", "tophat.param", package="systemPipeR")
read.delim(parampath, comment.char="#")
args <- suppressWarnings(systemArgs(sysma=parampath, mytargets=targetspath))
args
args<-systemArgs(sysma="param/trim.param", mytargets="targetsPE.txt")
```

