#directories
analysis_dir: '/Users/slsevilla/"Google Drive"/MyDocuments_Current/Education/"George Mason University"/Dissertation/Analysis'
aim_dir1: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/Analysis/Aim1'
aim_dir2: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/Analysis/Aim2'
aim_dir3: '/Users/slsevilla/Google\ Drive/MyDocuments_Current/Education/George\ Mason\ University/Dissertation/Analysis/Aim3'
aim_dir3_q: '/Users/slsevilla/"Google Drive"/MyDocuments_Current/Education/"George Mason University"/Dissertation/Analysis/Aim3'

backup_dir: 'e:/"My Files"/"My Files"/Dissertation/Analysis/Aim3/data'

data_dir: '/data/'
manifest_dir: '/manifest/'
notebook_dir: '/notebooks/'
img_dir: '/output/img/'
stats_dir: '/output/stats/'
taxonomy_dir: '/taxonomy/'
code_dir: '/general_code/'

# #################################################################
# #aim data
# aim = '3'
#
# #read in and set dir from yml
# yml_path = '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/Analysis/config_all.yml'
# with open(yml_path) as file:
#     dir_list = yaml.load(file, Loader=yaml.FullLoader)
#
# aim_search = 'aim_dir' + aim
# proj_dir = dir_list[aim_search].replace('\\','')
# data_dir = dir_list[aim_search + '_q'] + dir_list['data_dir']
#
# backup_dir = dir_list[backup_dir]
#
# manifest_dir = dir_list[aim_search].replace('\\','') + dir_list['manifest_dir']
# notebook_dir = dir_list[aim_search] + dir_list['notebook_dir']
# img_dir = dir_list[aim_search] + dir_list['img_dir']
# stats_dir = dir_list[aim_search] + dir_list['stats_dir']
# code_dir = dir_list['analysis_dir'] + dir_list['code_dir']
# #################################################################
# #updates to dir_list
# data_dir = data_dir + 'link_to_data.lnk'
#
# #################################################################
