
data_dir: 'C:\Users\slsevilla\Google Drive\MyDocuments_Current\Education\George Mason University\Dissertation\data\aim1\Project_NP0084_MB\'
git_dir: 'C:\Program Files\Git\Coding\gmu\dissertation\aim1\'
metadata_manifest: 'C:\Program Files\Git\Coding\gmu\dissertation\aim1\manifest\raw_manifest.txt'
variable_manifest: 'C:\Program Files\Git\Coding\gmu\dissertation\aim1\manifest\variable_manifest.txt'
binf_manifest: 'C:\Program Files\Git\Coding\gmu\dissertation\aim1\manifest\binf_manifest.txt'
clean_manifest: 'C:\Program Files\Git\Coding\gmu\dissertation\aim1\manifest\m_cleaned.txt'

analysis_dir: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/analysis/aim1/'
ref_dir: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/data/aim1/ref/'
qza_dir: '/Users/slsevilla/Google Drive/MyDocuments_Current/Education/George Mason University/Dissertation/data/aim1/final_qza/'
